.PHONY: atv1 atv2 atv3 atv4

atv1:
	javac -d .\bin .\src\App.java
	java -cp .\bin App 1200.00
	
atv2:
	javac -d .\bin .\src\App2.java
	java -cp .\bin App2 1200.00 10.00

atv3:
	javac -d .\bin .\src\Idade.java
	java -cp .\bin Idade 2003

atv4:
	javac -d .\bin .\src\Gato.java
	java -cp .\bin Gato 10 200